name: Format Code With Prettier

on:
  push:
    branches: [main] # Only run the workflow on pushes to the main branch
  workflow_dispatch: # Allow manual trigger via GitHub UI

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier on all files
        run: |
          npm run format  # Ensure the format script includes all files

      - name: Commit formatted code
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "chore: auto-format with Prettier" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
