name: Format Client Side Code With Prettier

on:
  push:
    branches: [client]

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci 
        # npm clean install (removes node_modules and installs fresh dependencies and
        # also installs the exact versions in package-lock.json, super cool!)

      - name: Run Prettier
        run: npm run format # I've created a format script in package.json

      - name: Commit formatted code
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "chore: auto-format with Prettier" || echo "No changes to commit"
          git push
